### ISSUE TITLE
DataFile not found 

### ISSUE THREAD

**Issue by vijayanant** [mfine/heroku-buildpack-stack#12]
I deployed a simple yesod app which depends on my private lib. The lib uses a data file.  My app serves static files fine. But the library is unable to read the data file 

`readFile =<< getDataFileName "datafile"`

I get the error 

`{"error":"/tmp/build_3f0a2590d91b5455b99261b26c6739f1/.stack-work/install/x86_64-linux/lts-6.4/7.10.3/share/x86_64-linux-ghc-7.10.3/my-lib/datafile: openFile: does not exist (No such file or directory)","message":"Internal Server Error"}`

Shouldn't it be looking at the `share` directory ? 

Am I missing anything?

**Comment by mfine** [comment]
@vijayanant not sure - what does you cabal file look like? Does it include the `datafile`? Do you have a `data-files` section in your cabal file? How are you deploying your private lib in relation to your app? Maybe if you send a listing of the files in your app and the contents of your cabal and stack.yaml files, could help figure out what's going on.

**Comment by vijayanant** [comment]
Here is cabal config for the lib

```
data-dir:            config
data-files:         datafile
```

The app's stack.yaml points to the repo location and commit. 

```
packages:
- '.'
- location:
    git: <lib repo>
    commit: 368380033480afb7df94a89f528ea6c6872817c1
  extra-dep: false
- location:
    git: <another repo>
    commit: 45cba469bf3769ed2bd4841e7a48e4f5635c1cb6
  extra-dep: false
```
